### ISSUE TITLE
Site not opening

### ISSUE THREAD

**Issue by Danielogenna** [caravan-bitcoin/caravan#70]
Hello, i tried to open the caravan site but it keeps telling me site can't be reached, maybe something can be done about this? @bucko13

**Comment by bucko13** [comment]
Hi @Danielogenna. Which "caravan site" are you referring to? https://caravanmultisig.com is working for me as is the github pages deployed one https://caravan-bitcoin.github.io/caravan/#/

**Comment by Danielogenna** [comment]
![Uploading Screenshot (195).png…]()
I have been trying to open the site since, but i keep getting this response, this is as regards to the project idea listed under summer of bitcoin, which i want to contribute to.

**Comment by bucko13** [comment]
Screenshot's not loading unfortunately. You should be able to run the site yourself if you're just trying to poke around. If you can share the error codes, I might be able to provide more information.

**Comment by Danielogenna** [comment]
Upon clicking this site https://caravanmultisig.com/ i get this javascript:diagnoseErrors()

But this link https://caravan-bitcoin.github.io/caravan/#/ just opened now.

This question (If you could redesign the Caravan Coordinator application from the ground up), i can't seem to find the application as stated or is it this site https://caravan-bitcoin.github.io/caravan/#/ ? Would be grateful if this can be answered, Thanks.

**Comment by jevidon** [comment]
Just tested and was unable to reproduce. Is this Javascript error something you are observing on any browser? And have you tried another device to see if the same issue persists?

**Comment by Danielogenna** [comment]
Just treid this site https://caravanmultisig.com/ using Firefox and was told this

The connection has timed out

The requested site did not respond to a connection request and the browser has stopped waiting for a reply.

Could the server be experiencing high demand or a temporary outage? Try again later.

Are you unable to browse other sites? Check the device’s network connection.

Is your device or network protected by a firewall or proxy? Incorrect settings can interfere with Web browsing.

Still having trouble? Consult your network administrator or Internet provider for assistance.

**Comment by Danielogenna** [comment]
But i want to confirm if these 2 sites are same thing?
https://caravanmultisig.com/ 
https://caravan-bitcoin.github.io/caravan/#/

**Comment by Danielogenna** [comment]
Can anyone clear my doubts here?

**Comment by robertshuford** [comment]
> But i want to confirm if these 2 sites are same thing?
> 
> https://caravanmultisig.com/ 
> 
> https://caravan-bitcoin.github.io/caravan/#/
> 
> 

They are the same version. They are updated through different methods, first one uses Vercel and the second uses a GitHub Action. Sometimes the vercel site will be ahead of the GitHub site by a patch version, but most of the time they should be the same version.

**Comment by Danielogenna** [comment]
Alright, thank you.

**Comment by Danielogenna** [comment]
Alright, thank you.

**Comment by Danielogenna** [comment]
Alright, thank you.
